### PR TITLE
Avoid top bar to overlay search bar in GNOME 40

### LINKED ISSUE #283: topbar overlay with the overview's search bar
i'm running on fedora 34 on x11

topbar overlay with the overview's search bar until there is an event

Steps to reproduce:
goto overview

Screenshot from 2021-05-04 10-39-23

### PR DESCRIPTION
**Pull request by aunetx**
This PR fixes #283 by adding a margin on the top of `Main.overview._overview._controls._searchEntryBin`, if and only if the option `show-in-overview` is enabled.

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thanks for your contribution, looks great!

However, I would prefer if the amount of margin added agree exactly with the height of the panel (use `PanelBox.height` for that). Can you adapt your PR to include this instead of using the  `24px` value?

File: panelVisibilityManager.js [hunk 1]
```diff
@@ -304,6 +305,11 @@ var PanelVisibilityManager = class HideTopBar_PanelVisibilityManager {
     
     _updateSettingsShowInOverview() {
         this._showInOverview = this._settings.get_boolean('show-in-overview');
+        if (this._showInOverview) {
+            _searchEntryBin.set_style("margin-top: 24px;");
```
Comment (tuxor1337) [inline panelVisibilityManager.js:309]:
```suggestion
            _searchEntryBin.set_style(`margin-top: ${PanelBox.height}px;`);
```

**Comment by aunetx** [comment]
Thanks for the review, I committed this!

I initially fixed the width to 24px because more makes a pretty big margin, but it's better not to hardcode it anyway :)

**Comment by aunetx** [comment]
@tuxor1337 sadly this does not seem to work well using `panelBox.height`, at least for me...

There are two issues:

- when logging in, the panel height seems to be detected as 0, so the style is `margin-top: 0px;`, which does nothing. We need an to detect when the panel is set to the right height, which can be done for example with `Main.layoutManager.panelBox.connect('notify::height', ()=>{...});`
- when using HIDPI display (mine is 2x zoomed), panel height is not 29px anymore with adwaita, but scaling*29px in height (58px for me). These 58px translate to 116px after this, because gnome scales up css styling using HIDPI scaling. In consequence, there is a (very big) gap on top of overview.

I will open another PR to fix all of this.

**Comment by ebrattli** [comment]
This seems to be causing the following issue #301. Please consider fixing this or reverting the change temporarily.

**Comment by tuxor1337** [comment]
@aunetx Thanks for your suggestion, this is fixed in 47f2193

**Comment by aunetx** [comment]
Cool thanks a lot! Now this should work for everything :)
